# Workflow used to update directus server 
name: cms-db-prod

on:
  push:
    branches: [ "releases/prod" ]
    paths: 
      - 'cms/scripts/pg-update.sh'
      - 'cms/scripts/pg-yamltodb.sh'
      - 'cms/snapshot/CMS-DB.yaml'
      - 'docker-files/CMS-DB.Dockerfile'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: releases/prod-cms
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Build docker container image 
    - run: docker build . -f docker-files/CMS-DB.Dockerfile -t "${{ secrets.DB_DOCKER_IMAGE }}"
    # Stop and remove old docker container (https://stackoverflow.com/questions/34228864/stop-and-delete-docker-container-if-its-running)
    - run: docker stop "${{ secrets.DB_DOCKER_CONTAINER }}" || true && docker rm "${{ secrets.DB_DOCKER_CONTAINER }}" || true
    # Start new container (without -d)
    - run: > 
        docker run
        --env="DB_HOST=${{ secrets.DB_HOST }}"
        --env="DB_PORT=${{ secrets.DB_PORT }}"
        --env="DB_DATABASE=${{ secrets.DB_DATABASE }}"
        --env="DB_USER=${{ secrets.DB_USER }}"
        --env="DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
        --name=${{ secrets.DB_DOCKER_CONTAINER }}
        ${{ secrets.DB_DOCKER_IMAGE }}

    # Delete container
    - run: docker stop "${{ secrets.DB_DOCKER_CONTAINER }}" || true && docker rm "${{ secrets.DB_DOCKER_CONTAINER }}" || true
 